[package]
name = "minigrep"
version = "0.1.0"
edition = "2021"
description = "A miniature version of the classic command line search tool grep."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
